#!/usr/bin/env python3
"""TODO item 1b: re-score headline metrics on the leak-free subsets.

Consumes merged_predictions.json + out/leakfree_ids.json (from 01_leakage_audit.py).
First reproduces the paper's published full-set numbers as a sanity gate
(PBE-ALIGNN non-metal MAE ~0.27, SlakoNet ~1.78, SlakoNet metal ~0.024),
then emits full -> leak-free comparisons with bootstrap CIs, functional-shift
slopes, and an auto-drafted verdict line.

Run:  python3 02_rescore_leakfree.py
Output: out/rescore_tables.md  (drop-in for rebuttal_E1YH.md §1 and AC response §1)
"""

import argparse
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import (
    GAP_KEYS,
    MERGED_PREDICTIONS,
    OUT_DIR,
    bootstrap_ci,
    load_merged,
    mae,
    md_table,
    r2,
)

SANITY = {  # (model, subset): (expected MAE, tolerance)
    ("PBE-ALIGNN", "nonmetal"): (0.27, 0.02),
    ("SlakoNet", "nonmetal"): (1.78, 0.02),
    ("SlakoNet", "metal"): (0.024, 0.005),
}


def subset_metrics(rows, key):
    ref = np.array([r["pbe_ref"] for r in rows], float)
    pred = np.array([r[key] for r in rows], float)
    metal = ref <= 0.0
    out = {}
    for name, mask in (("metal", metal), ("nonmetal", ~metal)):
        y, p = ref[mask], pred[mask]
        lo, hi = bootstrap_ci(y, p)
        out[name] = {"n": int(mask.sum()), "mae": mae(y, p), "ci": (lo, hi), "r2": r2(y, p)}
    return out


def fmt(m):
    return f"{m['mae']:.3f} [{m['ci'][0]:.3f}, {m['ci'][1]:.3f}]"


def shift_slope(rows, key):
    """Least-squares fit of model prediction vs PBE reference on non-metals."""
    ref = np.array([r["pbe_ref"] for r in rows], float)
    pred = np.array([r[key] for r in rows], float)
    m = ref > 0
    A = np.vstack([ref[m], np.ones(m.sum())]).T
    (slope, intercept), *_ = np.linalg.lstsq(A, pred[m], rcond=None)
    return float(slope), float(intercept)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--merged", default=MERGED_PREDICTIONS)
    ap.add_argument("--leakfree", default=os.path.join(OUT_DIR, "leakfree_ids.json"))
    args = ap.parse_args()

    rows = load_merged(args.merged)
    with open(args.leakfree) as f:
        leakfree = json.load(f)
    by_id = {r["mat_id"]: r for r in rows}

    # ---- sanity gate ----
    full = {model: subset_metrics(rows, key) for model, key in GAP_KEYS.items()}
    failures = []
    for (model, subset), (exp, tol) in SANITY.items():
        got = full[model][subset]["mae"]
        if abs(got - exp) > tol:
            failures.append(f"{model}/{subset}: got {got:.3f}, paper {exp}")
    if failures:
        sys.exit("SANITY GATE FAILED - do not trust leak-free numbers:\n  " + "\n  ".join(failures))
    print("sanity gate passed: full-set metrics reproduce the paper's published numbers")

    # ---- full -> leak-free per model ----
    lines = ["# Leak-free re-scoring (generated by 02_rescore_leakfree.py)", ""]
    table = []
    lf_metrics = {}
    for model, key in GAP_KEYS.items():
        # leakfree_ids.json keys are full checkpoint names, e.g. "PBE-ALIGNN (mp_gappbe)"
        ids = next((v for k, v in leakfree.items() if k.startswith(model)), None)
        if ids is None and model == "SlakoNet":
            # no fit-set audit: use the JARVIS-DFT row as the documented upper bound
            ids = next((v for k, v in leakfree.items() if "jv_mbj" in k or "mBJ" in k), None)
        if ids is None:
            continue
        sub = [by_id[i] for i in ids if i in by_id]
        lf = subset_metrics(sub, key)
        lf_metrics[model] = lf
        table.append(
            (
                model,
                f"{fmt(full[model]['nonmetal'])} -> {fmt(lf['nonmetal'])}",
                f"{fmt(full[model]['metal'])} -> {fmt(lf['metal'])}",
                f"{full[model]['nonmetal']['r2']:.3f} -> {lf['nonmetal']['r2']:.3f}",
                len(sub),
            )
        )
    lines.append("## Headline metrics, full -> leak-free (MAE eV [95% bootstrap CI])")
    lines.append(
        md_table(
            ["Model", "Non-metal MAE full -> leak-free", "Metal MAE full -> leak-free",
             "Non-metal R2 full -> leak-free", "Leak-free N"],
            table,
        )
    )
    lines.append("")

    # ---- functional-shift slopes on the ALIGNN-union leak-free set ----
    alignn_sets = [set(v) for k, v in leakfree.items() if "ALIGNN" in k]
    union_lf = [by_id[i] for i in set.intersection(*alignn_sets)] if alignn_sets else []
    lines.append("## Functional-shift calibration (prediction vs PBE reference, non-metals)")
    srows = []
    for model in ("mBJ-ALIGNN", "OptB88vdW-ALIGNN"):
        key = GAP_KEYS[model]
        s_full = shift_slope(rows, key)
        s_lf = shift_slope(union_lf, key) if union_lf else (float("nan"),) * 2
        srows.append(
            (model, f"m={s_full[0]:.3f}, c={s_full[1]:.3f}",
             f"m={s_lf[0]:.3f}, c={s_lf[1]:.3f}", len(union_lf))
        )
    lines.append(md_table(["Model", "Full set", "Leak-free (ALIGNN-joint)", "N leak-free"], srows))
    lines.append("")

    # ---- auto-drafted verdict (REVIEW BEFORE PASTING) ----
    order_full = sorted(full, key=lambda m: full[m]["nonmetal"]["mae"])
    order_lf = sorted(lf_metrics, key=lambda m: lf_metrics[m]["nonmetal"]["mae"])
    ranking_holds = [m for m in order_full if m in lf_metrics] == order_lf
    if "PBE-ALIGNN" in lf_metrics and "SlakoNet" in lf_metrics:
        adv_full = full["SlakoNet"]["nonmetal"]["mae"] - full["PBE-ALIGNN"]["nonmetal"]["mae"]
        adv_lf = (lf_metrics["SlakoNet"]["nonmetal"]["mae"]
                  - lf_metrics["PBE-ALIGNN"]["nonmetal"]["mae"])
    else:
        adv_full = adv_lf = float("nan")
    verdict = (
        f"AUTO-DRAFT VERDICT (review before pasting): the non-metal accuracy ranking "
        f"{'IS UNCHANGED' if ranking_holds else 'CHANGES'} on the leak-free subset "
        f"(full: {' < '.join(order_full)}; leak-free: {' < '.join(order_lf)}); "
        f"the PBE-ALIGNN advantage over SlakoNet moves from {adv_full:.3f} to {adv_lf:.3f} eV."
    )
    lines += ["## Verdict", "", verdict, ""]

    os.makedirs(OUT_DIR, exist_ok=True)
    out = os.path.join(OUT_DIR, "rescore_tables.md")
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print("\n".join(lines))
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
