#!/usr/bin/env python3
"""TODO item 2: discovery funnel vs. simpler baselines, from existing predictions only.

Implements the paper's six-stage funnel (Section 7) and compares it against
ALIGNN-only and SlakoNet-only screening on the same pool, judged against the
Alexandria PBE reference gap. Self-checks against the paper's reported
attrition (367 / 61 / 36 leads).

Run:  python3 03_funnel_baseline.py
Output: out/funnel_tables.md  (drop-in tables for rebuttal_wLVm.md §3 and AC response §3)
"""

import argparse
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import MERGED_PREDICTIONS, OUT_DIR, load_merged, md_table

OPEN_SHELL_TM = {"Mn", "Cr", "Fe", "Co", "Ni", "V", "Ru", "Tc", "Mo"}
ALKALI = {"Li", "Na", "K", "Rb", "Cs"}
# Be excluded: the paper's Table 3 counts (19,242 at stage 3) are only reproduced
# with the alkaline-earth set {Mg, Ca, Sr, Ba}; including Be removes 8 more
# structures and yields 366 leads in the 0.5-1.5 eV window instead of 367.
ALKALINE_EARTH = {"Mg", "Ca", "Sr", "Ba"}
NOBLE = {"He", "Ne", "Ar", "Kr", "Xe"}
Z_MAX = 57
SK_METAL_GUARD = 0.05     # stage 4: sk gap >= 0.05 eV
AGREEMENT_CUT = 0.5       # stage 6: |sk - alignn_pbe| < 0.5 eV
WINDOWS = {
    "IR / PV (0.5-1.5 eV)": (0.5, 1.5, 367),
    "Visible / Si-replacement (1.5-2.0 eV)": (1.5, 2.0, 61),
    "Wide-gap power / UV (2.5-3.0 eV)": (2.5, 3.0, 36),
}


def elements_of(formula):
    from pymatgen.core import Composition

    return {el.symbol for el in Composition(formula).elements}


def zmax_of(els):
    from pymatgen.core import Element

    return max(Element(e).Z for e in els)


def stage3_excluded(els):
    if els & OPEN_SHELL_TM:
        return True
    if "F" in els and els & (ALKALI | ALKALINE_EARTH):
        return True
    return False


def in_window(x, lo, hi):
    return lo <= x <= hi


def evaluate(passed, pool, lo, hi, pred_key):
    """Precision/recall/error of a candidate list against pbe_ref."""
    n_pass = len(passed)
    truth_pool = [r for r in pool if in_window(r["pbe_ref"], lo, hi)]
    tp = [r for r in passed if in_window(r["pbe_ref"], lo, hi)]
    precision = len(tp) / n_pass if n_pass else float("nan")
    recall = len(tp) / len(truth_pool) if truth_pool else float("nan")
    med_err = (
        float(np.median([abs(r[pred_key] - r["pbe_ref"]) for r in passed]))
        if passed
        else float("nan")
    )
    return n_pass, precision, recall, med_err


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--merged", default=MERGED_PREDICTIONS)
    args = ap.parse_args()

    rows = load_merged(args.merged)
    print(f"pool: {len(rows)} rows")

    # Precompute element sets once (pymatgen Composition is the slow part).
    els_cache = {}
    for r in rows:
        if r["formula"] not in els_cache:
            els_cache[r["formula"]] = elements_of(r["formula"])
        r["_els"] = els_cache[r["formula"]]

    # ---- shared funnel stages 1-4 ----
    s1 = rows
    s2 = [r for r in s1 if zmax_of(r["_els"]) <= Z_MAX and not (r["_els"] & NOBLE)]
    s3 = [r for r in s2 if not stage3_excluded(r["_els"])]
    s4 = [r for r in s3 if r["slakonet"] >= SK_METAL_GUARD]
    attrition = [
        ("1. Source (paired benchmark)", len(s1)),
        ("2. Z<=57, no noble gases", len(s2)),
        ("3. Failure-mode composition exclusion", len(s3)),
        ("4. sk gap >= 0.05 eV", len(s4)),
    ]
    for name, n in attrition:
        print(f"  {name}: {n}")

    lines = ["# Funnel vs. baselines (generated by 03_funnel_baseline.py)", ""]
    lines.append("## Stage-by-stage attrition (shared stages)")
    lines.append(md_table(["Stage", "N remaining"], attrition))
    lines.append("")

    for wname, (lo, hi, paper_n) in WINDOWS.items():
        # Failure-aware funnel, stages 5-6
        s5 = [
            r
            for r in s4
            if in_window(r["slakonet"], lo, hi) and in_window(r["alignn_pbe"], lo, hi)
        ]
        s6 = [r for r in s5 if abs(r["slakonet"] - r["alignn_pbe"]) < AGREEMENT_CUT]
        funnel = sorted(s6, key=lambda r: r["e_form"])

        flag = "OK" if len(funnel) == paper_n else f"MISMATCH (paper: {paper_n})"
        print(f"{wname}: funnel leads = {len(funnel)}  [{flag}]")

        # Baseline (a): ALIGNN-only threshold screen on the untouched pool
        alignn_only = sorted(
            [r for r in rows if in_window(r["alignn_pbe"], lo, hi)],
            key=lambda r: r["e_form"],
        )
        # Baseline (b): SlakoNet-only (metallic guard + window), no ALIGNN
        sk_only = sorted(
            [
                r
                for r in rows
                if r["slakonet"] >= SK_METAL_GUARD and in_window(r["slakonet"], lo, hi)
            ],
            key=lambda r: r["e_form"],
        )

        table = []
        for label, cand, pred_key in [
            ("Failure-aware funnel (paper)", funnel, "alignn_pbe"),
            ("ALIGNN-only", alignn_only, "alignn_pbe"),
            ("SlakoNet-only", sk_only, "slakonet"),
        ]:
            n, prec, rec, med = evaluate(cand, rows, lo, hi, pred_key)
            table.append(
                (label, n, f"{prec:.3f}", f"{rec:.3f}", f"{med:.3f}")
            )
        lines.append(f"## {wname}  (funnel self-check: {len(funnel)} vs paper {paper_n})")
        lines.append(
            md_table(
                [
                    "Workflow",
                    "Candidates passed",
                    "Precision (pbe_ref in window)",
                    "Recall vs pool",
                    "Median |gap err| (eV)",
                ],
                table,
            )
        )
        lines.append("")

    os.makedirs(OUT_DIR, exist_ok=True)
    out = os.path.join(OUT_DIR, "funnel_tables.md")
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
